namespace: monitoring
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus-with-endpoints-role.yml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - statefulset.yaml
  - service.yaml
