apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  # serviceMonitorSelector:
  #   matchLabels:
  #     app.kubernetes.io/component: rabbitmq
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
