apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kserve-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # not to delete AppProject before deleting its Applications
spec:
  description: kserve-test

  sourceRepos:
    - "*"

  destinations:
    - namespace: kserve-test
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy

  orphanedResources:
    warn: false
