site_name: Kubernetes Traning
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
  features:
    - header.autohide
    - navigation.indexes
    - toc.follow
    - navigation.tracking # the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
repo_url: https://github.com/nakamasato/kubernetes-training
markdown_extensions:
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-9NTB93RVPJ
docs_dir: contents
