apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    prometheus: prometheus # this label is used for endpoints, which is eventually used by ServiceMonitor
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
