    CREATE TABLE stat (num SMALLINT, started_at DATETIME, updated_at DATETIME);
    INSERT INTO stat VALUES
        (10000, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY + INTERVAL 20 MINUTE),
        (10000, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY + INTERVAL 30 MINUTE),
        (5000, NOW() - INTERVAL 5 HOUR, NOW() - INTERVAL 5 HOUR + INTERVAL 10 MINUTE),
        (100, NOW() - INTERVAL 5 HOUR, NOW() - INTERVAL 5 HOUR + INTERVAL 20 MINUTE);
