apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq-producer
  name: rabbitmq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq-producer
    spec:
      containers:
      - image: nakamasato/rabbitmq-producer
        name: rabbitmq-producer
        resources: {}
status: {}
