apiVersion: v1
data:
  MYSQL_PASSWORD: {{ default "" .Values.mysql.password | b64enc }}
kind: Secret
metadata:
  name: {{ include "helm-example.fullname" . }}-uwsgi
  labels:
    {{- include "helm-example.labels" . | nindent 4 }}
