apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
    resources:
      requests:
        memory: 1Gi
        cpu: 80m
      limits:
        memory: 1Gi
        cpu: 1000m
    jvmOptions:
      -Xms: 800m
      -Xmx: 800m
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        memory: 512Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 1000m
    jvmOptions:
      -Xms: 400m
      -Xmx: 400m
  entityOperator:
    topicOperator: {}
    userOperator: {}
