apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.8.0
  replicas: 1
  consumer:
    bootstrapServers: my-source-cluster-kafka-bootstrap:9093
    groupId: my-source-group-id
    tls:
      trustedCertificates:
        - secretName: my-source-cluster-cluster-ca-cert
          certificate: ca.crt
  producer:
    bootstrapServers: my-target-cluster-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: my-target-cluster-cluster-ca-cert
          certificate: ca.crt
  include: ".*"
