apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.8.0
  replicas: 1
  consumer:
    bootstrapServers: my-source-cluster-kafka-bootstrap:9092
    groupId: my-source-group-id
  producer:
    bootstrapServers: my-target-cluster-kafka-bootstrap:9092
  include: ".*"
