apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredPrefixes
metadata:
  name: ns-must-start-with-prefix
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    prefix: "dev"
