apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              name: datasources
              readOnly: false
              subPath: datasource.yaml
            - mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
              name: dashboards
              readOnly: false
              subPath: dashboard.yaml
            - mountPath: /var/lib/grafana/dashboards/rabbitmq.json
              name: dashboards
              readOnly: false
              subPath: rabbitmq.json
            - mountPath: /var/lib/grafana/dashboards/mysql-test.json
              name: dashboards
              readOnly: false
              subPath: mysql-test.json
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: datasources
          configMap:
            defaultMode: 420
            name: datasources
        - name: dashboards
          configMap:
            defaultMode: 420
            name: dashboards
        - name: custom-config
          configMap:
            name: custom-config
