apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq-consumer
  name: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - image: nakamasato/rabbitmq-consumer
        name: rabbitmq-consumer
        resources: {}
status: {}
