# Default values for helm-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: ""

uwsgi:
  image:
    repository: nakamasato/flask-test
    pullPolicy: IfNotPresent
    tag: ""

service:
  type: ClusterIP
  port: 80

mysql:
  host: mysql.database.svc.cluster.local
  port: 3306
  user: user
  database: test
  password: password
