apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: piyasara-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /flights
            pathType: Exact
            backend:
              service:
                name: piyasara-service
                port:
                  number: 8761
          - path: /horas
            pathType: Exact
            backend:
              service:
                name: hora-service
                port:
                  number: 5761
