apiVersion: 1
datasources:
  - access: proxy
    editable: true
    name: prometheus
    orgId: 1
    type: prometheus
    url: http://prometheus.monitoring.svc:9090
    version: 1

  - name: mysql
    type: mysql
    url: mysql.database.svc.cluster.local:3306
    database: test_db
    user: grafana
    secureJsonData:
      password: password
