apiVersion: v1
data:
  MYSQL_DATABASE: test
  MYSQL_HOST: mysql.database.svc.cluster.local
  MYSQL_PORT: "3306"
  MYSQL_USER: user
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kustomize-example-uwsgi
