apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-example
  name: kustomize-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-example
  template:
    metadata:
      labels:
        app: kustomize-example
    spec:
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf

        - image: nakamasato/flask-test
          imagePullPolicy: Always
          name: uwsgi
          envFrom:
            - configMapRef:
                name: kustomize-example-uwsgi
            - secretRef:
                name: kustomize-example-uwsgi

      volumes:
        - name: nginx-conf
          configMap:
            name: kustomize-example-nginx
            items:
              - key: nginx.conf
                path: nginx.conf
