commonLabels:
  app: kustomize-example
resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - secret.yaml
configMapGenerator:
  - name: kustomize-example-nginx
    files:
    - nginx.conf
