apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-example
  name: kustomize-example
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"

        - name: uwsgi
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
