apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app-with-service-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app-with-service-monitor
  endpoints:
  - port: web
