apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pets.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                breed:
                  type: string
                owner:
                  type: string
            status:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: pets
    singular: pet
    kind: Pet
    listKind: PetList
