kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: aWXoVZHpNfToTWZ6cOVhMH4Nq+3mwntOz89+MnBgdf8=
      - identity: {}
