name: pre-commit
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-python@v6
        with:
          python-version: 'pypy3.9'
      - uses: pre-commit/action@v3.0.1
