name: update-readme

on:
  schedule:
    - cron:  '0 0 * * MON'
  push:
    branches:
      - main
  pull_request:


env:
  BRANCH_NAME: update-date-in-readme
  BASE_BRANCH_NAME: main
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-pr-if-outdated:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}

      - name: update argocd version in readme.yml
        run: |
          argocd_version=$(kubectl kustomize contents/argocd/setup | yq 'select(.kind == "Deployment").spec.template.spec.containers[] | select(.name == "argocd-server").image' | sed 's/.*:\(.*\)/\1/')
          echo $argocd_version
          yq -i "(.versions[] | select(.name == \"ArgoCD\").version) = \"$argocd_version\"" readme.yml

      - name: update strimzi version in readme.yml
        run: |
          strimzi_version=$(kubectl kustomize contents/strimzi/cluster-operator/overlays/kafka/ | yq 'select(.kind == "Deployment").spec.template.spec.containers[] | select(.name == "strimzi-cluster-operator").image' | sed 's/.*:\(.*\)/\1/')
          echo $strimzi_version
          # yq -i "(.versions[] | select(.name == \"Strimzi\").version) = \"$strimzi_version\"" readme.yml

      - name: update prometheus-operator version in readme.yml
        run: |
          prometheus_operator_version=$(kubectl kustomize contents/prometheus-operator/ | yq 'select(.kind == "Deployment").spec.template.spec.containers[] | select(.name == "prometheus-operator").image' | sed 's/.*:\(.*\)/\1/')
          echo $prometheus_operator_version
          # yq -i "(.versions[] | select(.name == \"Prometheus-Operator\").version) = \"$prometheus_operator_version\"" readme.yml

      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: ^1.18

      - name: update readme
        run: go run readme.go

      - name: check if need to commit
        id: need_commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::set-output name=need_commit::true
          else
            echo "::set-output name=need_commit::false
          fi

      - name: update date in readme and commit
        if: steps.need_commit.outputs.need_commit == 'true'
        id: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{ env.BRANCH_NAME }}
          git add .
          git commit -m 'update readme'
          git push -u origin HEAD -f # nothing to commit

      - name: check if pr exists
        if: steps.need_commit.outputs.need_commit == 'true'
        id: check_pr
        run: |
          echo "::set-output name=count::$(gh pr list -S head:${{ env.BRANCH_NAME }} -B ${{ env.BASE_BRANCH_NAME }} | wc -l)"

      - name: create pr
        if: ${{ steps.need_commit.outputs.need_commit == 'true' && steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B "${{ env.BASE_BRANCH_NAME }}" -t "Update version in README" -b ""
